### ISSUE TITLE
Ability to allow/disallow certain text fields

### ISSUE THREAD

**Issue by markgrahamdunn** [contentsync/SketchContentSync#65]
Would there be a possibility in a future release to exclude certain text fields using a key e.g ~aTextfield...  or turn it around, only text fields with a certain char / key will be pushed to google sheets?

**Comment by dbrody** [comment]
Yes, we can look into creating some option to enable/disable syncing on a layer. We'd like to avoid special naming on the layer since it may interfere with other plugins / conventions. Any ideas would be welcomed and we will look into options as well. Thanks for the comment!

**Comment by markgrahamdunn** [comment]
hi @dbrody thanks for your prompt reply.
i would consider using a ∞ or ~ prefix to omit sending values of certain textfields. Would love to have this working on Artboard and Page level.

a.t.m my Symbol page gets automatically uploaded to google sheets while i would prefer this wouldn't happen.

**Comment by dbrody** [comment]
Our initial version of this takes a slightly different approach. We'd love to hear your thoughts.

We are thinking about it as built into the Sketch context menu instead of making it based on layer name. So if you right click on the page or any selection of layers, you have the option to enable/disabled syncing on it.

At the page level:
![screen shot 2017-09-20 at 7 53 07 am](https://user-images.githubusercontent.com/210322/30651686-525861fa-9ddb-11e7-9487-5509692ebb8c.png)

For selected layers:
![screen shot 2017-09-20 at 7 53 29 am](https://user-images.githubusercontent.com/210322/30651695-5799a200-9ddb-11e7-8406-71dfba90a2f4.png)

The sidebar will gray out the push/pull if all selected layers or the current page is disabled. This is a helpful hint to know if it is enabled or disabled:
![screen shot 2017-09-20 at 8 13 17 am](https://user-images.githubusercontent.com/210322/30651810-9e6be904-9ddb-11e7-9d4a-b018110c6450.png)

 The menu will also only make the options that are currently applicable enabled:
![screen shot 2017-09-20 at 8 13 53 am](https://user-images.githubusercontent.com/210322/30651837-a9c1ed62-9ddb-11e7-859d-95938b82ea0e.png)

What do you think?

**Comment by dbrody** [comment]
@markgrahamdunn -

For now, as a work around, you can utilize the "Selective Sync" feature where if you have layers selected, only those layers will be synchronized.

So if you were to do a `Cmd + A` and select all the layers of a page and sync, only that page will be synced.

**Comment by markgrahamdunn** [comment]
Hi @dbrody,

my apologies for the late reply.. Work load tends to creep up in life.

I like your suggested proposal but would this contextual functionality also be available as an option if a user control + click's on a Page name (under Pages) or Artboard name instead of relying on a canvas interaction (page level)?
Also would you intend to have a visual cue in the Layer lists & Page list or leave it like it currently is.?
Example an icon next to a page name, artboard name, layer name that hints if an Page, Artboard or Layer has Sync enabled?

My impression is having a single greyed-out icon in the Sidebar as a hint gives the impression that the functionality is not working (disabled) and also doesn't give valid feedback on a granular level.

**Comment by markgrahamdunn** [comment]
regarding the "Selective Sync" feature:

**Comment by dbrody** [comment]
@markgrahamdunn - Thanks for the great feedback. We're excited to prepare for launch this feature with even better Sketch integration than before. :) Check it out...

Our initial approach is a simple strikethrough on the layer list when a layer is disabled for sync. If this proves to be too much of an interference in common usage we will eventually migrate it to some other symbolism such as an image or something. Any ideas would be welcome!

### Enabling / Disabling an entire Page:
![screen shot 2018-01-06 at 10 40 39 am](https://user-images.githubusercontent.com/210322/34642849-0f21554c-f2cf-11e7-9b06-225a35e00741.png)
![screen shot 2018-01-06 at 10 40 50 am](https://user-images.githubusercontent.com/210322/34642850-13717d98-f2cf-11e7-8611-de170d2dd351.png)
![screen shot 2018-01-06 at 10 41 01 am](https://user-images.githubusercontent.com/210322/34642852-17ace5e6-f2cf-11e7-81d9-2c2df70a5518.png)

### Enabling / Disabling Layers:
![screen shot 2018-01-06 at 10 41 09 am](https://user-images.githubusercontent.com/210322/34642859-40aa880e-f2cf-11e7-9ddc-c6fbd0d304d6.png)
![screen shot 2018-01-06 at 10 45 30 am](https://user-images.githubusercontent.com/210322/34642861-4600e708-f2cf-11e7-867c-5f60b01407e2.png)
![screen shot 2018-01-06 at 10 46 51 am](https://user-images.githubusercontent.com/210322/34642865-55401a7c-f2cf-11e7-9aac-52310e3b5d39.png)

### Toggling Direct on the Draw View
![screen shot 2018-01-06 at 10 46 51 am](https://user-images.githubusercontent.com/210322/34642871-6a7d38ca-f2cf-11e7-9d71-ffaf55ba58f9.png)

This will be rolling out soon in our next release in the coming week.

**Comment by dbrody** [comment]
@markgrahamdunn - This feature is going live with release 3.1.1 (#67)

**Comment by dbrody** [comment]
Released with 3.1.1
