### ISSUE TITLE
Refreshing List and Syncing push / pull takes a lot of time

### ISSUE THREAD

**Issue by markgrahamdunn** [contentsync/SketchContentSync#83]
Lately the syncing & refreshing of lists and keys with their values take a lot of time.
Could this be related to the amount of lists and or duplicate naming of lists?

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1683184/43715658-77f24e42-9981-11e8-9000-5cfd2d4265cd.png">

**Comment by dbrody** [comment]
That list is synced from your Google Spreadsheet each time at the moment when it is refreshed. It would definitely be impacted by the number of versions and the number of sheets. There may be some optimization that can be done here so I'll follow up on this.

**Comment by markgrahamdunn** [comment]
@dbrody in worst case scenario it can take up to 2 minutes to sync.

![untitled 2](https://user-images.githubusercontent.com/1683184/44099758-9e6cd84a-9fe3-11e8-99e1-5972459f7afb.gif)

**Comment by dbrody** [comment]
@markgrahamdunn - There are a couple of things that influence this: Google API response time, ContentSync makes a few requests to get the proper meta data for a sync, and a large sync can also be a large amount of data depending on some of the options toggled. All this can add up the time to fetch the data and apply the updates.

We have also upgraded our servers since we noticed the increased traffic has been causing some issues. We are also investigating some software improvements.

**Comment by markgrahamdunn** [comment]
@dbrody spoken with our designer and the amount of columns that (s)he / we need to sync back is 1 to 3 (including key) per sheet (pages) max in a project. If only the active column could be synced it would improve response time  / data sync.

**Comment by dbrody** [comment]
@markgrahamdunn - During a sync, only the syncing version is transferred so that shouldn't be an issue. The number of sheets, the number of keys as well as the types of keys (many symbol overrides, etc) may impact the amount of time as well.

We pull the data directly from Google spreadsheets so that is a main source of the delay. We do this so that all pull/pushes are up to date with the actual spreadsheet data.

We are working on a ContentSync hosted version where the data would be on our platform directly. In this scenario speeds will be drastically improved.

**Comment by markgrahamdunn** [comment]
@dbrody thanks for the explanation. i'll try to see on our end how we can optimise your sheets.

**Comment by dbrody** [comment]
@markgrahamdunn - We will also look on our end - it may take us a few days to dive in deeply though since this week is filling up quickly.

**Comment by dbrody** [comment]
@markgrahamdunn - It seems to be directly correlated to the number of sheets on a Google Spreadsheet. For each sheet, the processing time increases by a few seconds.

It seems to originate with Google's API which can take a long time to retrieve the data when there are many sheets. That is why we do store a list of versions on our side so hopefully you don't need to refresh your version list very often.

We are continuing to look into how we can improve the performance on this.

**Comment by dbrody** [comment]
This is a known issue with Google Spreadsheets API. More sheets = more time.
