### ISSUE TITLE
Ability to have the artboard name in the Google Spreadsheet

### ISSUE THREAD

**Issue by MattCowBoy** [contentsync/SketchContentSync#90]
Hi, 
it would be awesome to have another column before to the "keys" column, that reported the artboard's name where each layer is. This would help so much in identifying quickly the layer that it needs to be edited. It also reduce dramatically errors where there are more layer with the same name. #

**Comment by dbrody** [comment]
@MattCowBoy - What you could do is modify the Key Transform Function to include the Artboard name. So your keys could be "<Artboard> -> <Context> -> <Layer Name>" if you'd like. The fully customizable transform functions for keys and sheets allow you to customize naming to your liking. This is accessible using:

**Text layers:** `layer.parentArtboard().name()`
**Symbol Instances:** `contexts[0].parentArtboard().name()`

This is because the layer is always the text layer and contexts are the nested symbol instances the text layer appears in. For your use case, you'd probably want the artboard name of a text layer or the artboard name of the artboard the main symbol instance is on. So you'd probably do something like:

```js
var artboardName = "";
if(contexts && contexts.length > 0){
  // If symbol instance - page of the symbol instance
  artboardName = contexts[0].parentPage().name();
} else {
  // If text layer - page of the text layer
  artboardName = layer.parentPage().name();
}
```
And then use `artboardName` somewhere in your key transform function.

Let me know if you'd like help creating the transform function!

Also, if you check out the [ContentSync Desktop App](https://www.contentsync.io/home/desktop), it will give you a visual of the design so you can click through the design into the Google Spreadsheet.

**Comment by dbrody** [comment]
The above response is now out of date. We'll look into other possible solutions to this request.

**Comment by dbrody** [comment]
The new release now includes key prefix and suffix options which allow for adding artboard and page names:
![Screen Shot 2020-04-15 at 2 17 08 PM](https://user-images.githubusercontent.com/210322/79390048-d9083c80-7f23-11ea-8d5f-1dd77f3254b6.png)

You can select a default key prefix:
![Screen Shot 2020-04-15 at 2 17 14 PM](https://user-images.githubusercontent.com/210322/79390070-e4f3fe80-7f23-11ea-8cb0-faf2f479e363.png)

You can also select a unique key suffix:
![Screen Shot 2020-04-15 at 2 17 20 PM](https://user-images.githubusercontent.com/210322/79390079-eae9df80-7f23-11ea-8bf1-0d26b0c453f2.png)
